# ใช้อิมเมจพื้นฐานที่รองรับ systemd เช่น Ubuntu
จากอูบุนตู:20.04

# ติดตั้งแพ็คเกจที่จำเป็น
เรียกใช้การอัปเดต apt-get && \
apt-get ติดตั้ง -y shellinabox && \
apt-get ติดตั้ง -y systemd && \
ฉลาด-รับการทำความสะอาด && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
เรียกใช้ echo 'root:root' | chpasswd
# เปิดเผยพอร์ตเทอร์มินัลบนเว็บ
เปิดเผย 4200

# เริ่มเชลล์ลินาบ็อกซ์
CMD ["/usr/bin/shellinaboxd", "-t", "-s", "/:เข้าสู่ระบบ"]
